window.celebrations = [
  // Tháng 01 (các ngày lễ trong năm phụng vụ)
    { date: '02/01', type: 'M', feast: 'Thánh Basiliô Cả và Thánh Grêgôriô Nazianzênô, Giám mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
    { date: '03/01', type: 'O', feast: 'Danh Thánh Chúa Giêsu. (Tr).' },
    { date: '07/01', type: 'O', feast: 'Thánh Raimundô Penyafort, linh mục (Tr).' },
    { date: '13/01', type: 'O', feast: 'Thánh Hilariô, giám mục, tiến sĩ Hội Thánh (Tr).' },
    { date: '17/01', type: 'M', feast: 'Thánh Antôn, viện phụ.', chasuble: 'Tr' },
    { date: '20/01', type: 'O', feast: 'Thánh Fabianô, giáo hoàng, tử đạo (Đ). Thánh Sêbastianô, tử đạo (Đ).' },
    { date: '21/01', type: 'M', feast: 'Thánh Anê, trinh nữ, tử đạo.', chasuble: 'Đ' },
    { date: '22/01', type: 'M', feast: 'Thánh Vinh Sơn, phó tế, tử đạo.', chasuble: 'Đ' },
    { date: '24/01', type: 'M', feast: 'Thánh Phanxicô Salêsiô, giám mục, tiến sĩ Hội Thánh.', chasuble: 'Đ' },
    { date: '25/01', type: 'F', feast: 'THÁNH PHAOLÔ TÔNG ĐỒ TRỞ LẠI.', chasuble: 'Tr' },
    { date: '26/01', type: 'M', feast: 'Thánh Timôthêô và thánh Titô, giám mục.', chasuble: 'Tr' },
    { date: '27/01', type: 'O', feast: 'Thánh Angêla Mêrici, trinh nữ (Tr).' },
    { date: '28/01', type: 'M', feast: 'Thánh Tôma Aquinô, linh mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
    { date: '31/01', type: 'M', feast: 'Thánh Gioan Bosco, linh mục.', chasuble: 'Tr' },
        { date: '02/02', type: 'F', feast: 'DÂNG CHÚA GIÊSU TRONG ĐỀN THÁNH (Lễ Nến).', chasuble: 'Tr' },
        { date: '03/02', type: 'O', feast: 'Thánh Blasiô, giám mục, tử đạo (Đ). Thánh Ansgariô, giám mục (Tr).'},
        { date: '05/02', type: 'M', feast: 'Thánh Agatha, trinh nữ, tử đạo.', chasuble: 'Đ' },
        { date: '06/02', type: 'M', feast: 'Thánh Phaolô Miki và các bạn tử đạo.', chasuble: 'Đ' },
        { date: '08/02', type: 'O', feast: 'Thánh Giêrônimô Êmilianô (Tr). Thánh Jôsêphina Bakhita, trinh nữ (Tr).' },
        { date: '10/02', type: 'M', feast: 'Thánh Scholastica, trinh nữ.', chasuble: 'Tr' },
        { date: '11/02', type: 'O', feast: 'Đức Mẹ Lộ Đức (Tr). Ngày quốc tế bệnh nhân.' , chasuble: 'Tr' },
        { date: '14/02', type: 'M', feast: 'Thánh Cyrillô, đan sĩ và thánh Mêthôđiô, giám mục.', chasuble: 'Tr' },
        { date: '17/02', type: 'O', feast: 'Bảy thánh lập dòng Tôi Tớ Đức Trinh Nữ Maria (Tr).' },
        { date: '21/02', type: 'O', feast: 'Thánh Phêrô Đamianô, giám mục, tiến sĩ Hội Thánh (Tr).' },
        { date: '22/02', type: 'F', feast: 'LẬP TÔNG TÒA THÁNH PHÊRÔ.', chasuble: 'Tr' },
        { date: '23/02', type: 'M', feast: 'Thánh Pôlicarpô, giám mục, tử đạo.', chasuble: 'Đ' },
        { date: '27/02', type: 'O', feast: 'Thánh Grêgôriô Naracensiô viện phụ, tiến sĩ Hội Thánh.' },

 	      { date: '04/03', type: 'O', feast: 'Thánh Casimirô.' },
        { date: '07/03', type: 'O', feast: 'Thánh nữ Perpêtua và thánh nữ Fêlicita, tử đạo.' },
        { date: '08/03', type: 'O', feast: 'Thánh Gioan Thiên Chúa, tu si.' },
        { date: '18/03', type: 'O', feast: 'Thánh Cyrilô Giêrusalem, tiến sĩ Hội Thánh.' },
        { date: '23/03', type: 'O', feast: 'Thánh Turibiô Môgrôvêjô, giám mục.' },


        { date: '02/04', type: 'O', feast: 'Thánh Phanxicô Paola, ẩn tu.' },
        { date: '04/04', type: 'O', feast: 'Thánh Isiđôrô, giám mục, tiến sĩ Hội Thánh.' },
        { date: '05/04', type: 'O', feast: 'Thánh Vinh Sơn Ferrê, linh mục.' },
        { date: '07/04', type: 'O', feast: 'Thánh Gioan Lasan, linh mục.' },
        { date: '11/04', type: 'M', feast: 'Thánh Stanislaô, Giám mục.', chasuble: 'Đ' },
        { date: '13/04', type: 'O', feast: 'Thánh Martinô I, giáo hoàng, tử đạo (Đ).' },
        { date: '21/04', type: 'O', feast: 'Thánh Anselmô, giám mục, tiến sĩ Hội Thánh (Tr).' },
        { date: '23/04', type: 'O', feast: 'Thánh Giorgiô, tử đạo (Đ). Thánh Ađalbertô, giám mục, tử đạo (Đ).' },
        { date: '24/04', type: 'F', feast: 'KỶ NIỆM CUNG HIẾN NHÀ THỜ CHÍNH TÒA GIÁO PHẬN. (1983).', chasuble: 'Tr' },
        { date: '25/04', type: 'F', feast: 'THÁNH MARCÔ, TÁC GIẢ SÁCH TIN MỪNG.', chasuble: 'Đ' },
        { date: '28/04', type: 'O', feast: 'Thánh Phêrô Chanel, linh mục, tử đạo (Đ). Thánh Luy Grignion Montfort, linh mục (Tr).' },
        { date: '29/04', type: 'M', feast: 'Thánh Catarina Siêna, trinh nữ, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '30/04', type: 'O', feast: 'Thánh Piô V, giáo hoàng (Tr).' },


        { date: '01/05', type: 'O', feast: 'Thánh Giuse Thợ (Tr).' },
        { date: '02/05', type: 'M', feast: 'Thánh Athanasiô, giám mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '03/05', type: 'F', feast: 'THÁNH PHILIPPHÊ VÀ THÁNH GIACÔBÊ, Tông Đồ.', chasuble: 'Đ' },
        { date: '06/05', type: 'O', feast: 'Thánh Đaminh Saviô (Tr).'},
        { date: '12/05', type: 'O', feast: 'Thánh Nêrêô và thánh Achilêô, tử đạo (Đ). Thánh Pancratiô, tử đạo (Đ).' },
        { date: '13/05', type: 'O', feast: 'Đức Mẹ Fatima (Tr).' },
        { date: '14/05', type: 'F', feast: 'THÁNH MATTHIA, TÔNG ĐỒ.', chasuble: 'Đ' },
        { date: '18/05', type: 'O', feast: 'Thánh Gioan I, giáo hoàng, tử đạo (Đ).' },
        { date: '20/05', type: 'O', feast: 'Thánh Bernarđiô Siêna, linh mục (Tr).' },
        { date: '21/05', type: 'O', feast: 'Thánh Christophôrô Magallanes, linh mục, và các bạn, tử đạo (Đ).' },
        { date: '25/05', type: 'O', feast: 'Thánh Bêđa Khả Kính, linh mục, tiến sĩ Hội Thánh (Tr). Thánh Grêgôriô VII, giáo hoàng (Tr). Thánh Maria Magđalêna Pazzi, trinh nữ (Tr).' },
        { date: '26/05', type: 'M', feast: 'Thánh Philipphê Nêri, linh mục.', chasuble: 'Tr' },
        { date: '29/05', type: 'O', feast: 'Thánh Phaolô VI, giáo hoàng (Tr).' },
        { date: '31/05', type: 'F', feast: 'ĐỨC MARIA THĂM VIẾNG BÀ ÊLISABETH.', chasuble: 'Tr' },


        { date: '01/06', type: 'M', feast: 'Thánh Justinô, tử đạo.', chasuble: 'Đ' },
        { date: '02/06', type: 'O', feast: 'Thánh Marcellinô và thánh Phêrô, tử đạo (Đ).' },
        { date: '03/06', type: 'M', feast: 'Thánh Carôlô Lwanga và các bạn tử đạo.', chasuble: 'Đ' },
        { date: '05/06', type: 'M', feast: 'Thánh Bônifatiô, giám mục, tử đạo.', chasuble: 'Đ' },
        { date: '06/06', type: 'O', feast: 'Thánh Norbertô, giám mục (Tr).' },
        { date: '09/06', type: 'O', feast: 'Thánh Ephrem, phó tế, tiến sĩ Hội Thánh (Tr).' },
        { date: '11/06', type: 'M', feast: 'Thánh Barnaba, Tông Đồ.', chasuble: 'Đ' },
        { date: '13/06', type: 'M', feast: 'Thánh Antôn Pađôva, linh mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '19/06', type: 'O', feast: 'Thánh Romualđo, viện phụ (Tr).' },
        { date: '21/06', type: 'M', feast: 'Thánh Luy Gonzaga, tu sĩ.', chasuble: 'Tr' },
        { date: '22/06', type: 'O', feast: 'Thánh Paulinô, giám mục Nôla (Tr). Thánh Fisher, giám mục, tử đạo, thánh Tôma More, tử đạo (Đ).' },
        { date: '27/06', type: 'O', feast: 'Thánh Cyrillô Alexandria, tiến sĩ Hội Thánh (Tr).' },
        { date: '28/06', type: 'M', feast: 'Thánh Irênê, giám mục, tử đạo.', chasuble: 'Đ' },
        { date: '30/06', type: 'O', feast: 'Các thánh tử đạo tiên khởi của giáo đoàn Rôma (Đ).' },


        { date: '03/07', type: 'F', feast: 'THÁNH TÔMA, TÔNG ĐỒ.', chasuble: 'Đ' },
        { date: '04/07', type: 'O', feast: 'Thánh nữ ÊlisaBeth Bồ Đào Nhà (Tr).' },
        { date: '05/07', type: 'O', feast: 'Thánh Antôn Maria Zaccaria, linh mục (Tr).' },
        { date: '06/07', type: 'O', feast: 'Thánh Maria Gôretti, trinh nữ, tử đạo (Đ).' },
        { date: '09/07', type: 'O', feast: 'Thánh Augustinô Zhao Rong, linh mục, và các bạn, tử đạo (Đ).' },
        { date: '11/07', type: 'M', feast: 'Thánh Bênêđictô, viện phụ.', chasuble: 'Tr' },
        { date: '13/07', type: 'O', feast: 'Thánh Henricô (Tr).' },
        { date: '14/07', type: 'O', feast: 'Thánh Camillô Lellis, linh mục (Tr).' },
        { date: '15/07', type: 'M', feast: 'Thánh Bônaventura, giám mục, tiến sĩ Hội thánh.', chasuble: 'Tr' },
        { date: '16/07', type: 'O', feast: 'Đức Mẹ núi Carmêlô (Tr).' },
        { date: '20/07', type: 'O', feast: 'Thánh Apôllinarê, giám mục tử đạo (Đ).' },
        { date: '21/07', type: 'O', feast: 'Thánh Laurensô Brinđisi, linh mục, tiến sĩ Hội Thánh (Tr).' },
        { date: '22/07', type: 'F', feast: 'THÁNH NỮ MARIA MAGĐALÊNA.', chasuble: 'Tr' },
        { date: '23/07', type: 'O', feast: 'Thánh Birgitta, nữ tu (Tr).' },
        { date: '24/07', type: 'O', feast: 'Thánh Sarbêliô Makhluf, linh mục (Tr).' },
        { date: '25/07', type: 'F', feast: 'THÁNH GIACÔBÊ, TÔNG ĐỒ.', chasuble: 'Đ' },
        { date: '26/07', type: 'M', feast: 'Thánh Gioa-Kim và thánh Anna, song thân Đức Maria.', chasuble: 'Tr' },
        { date: '29/07', type: 'M', feast: 'Thánh Nữ Martha, Maria và Lazarô.', chasuble: 'Tr' },
        { date: '30/07', type: 'O', feast: 'Thánh Phêrô Kim Ngôn, giám mục tiến sĩ Hội Thánh (Tr).' },
        { date: '31/07', type: 'M', feast: 'Thánh Ignatiô Loyôla, linh mục.', chasuble: 'Tr' },


        { date: '01/08', type: 'M', feast: 'Thánh Alphongsô Maria Liguori, giám mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '02/08', type: 'O', feast: 'Thánh Êusêbiô Vercellêsi (Tr). Thánh Phêrô Julianô Eymand, linh mục (Tr)' },
        { date: '04/08', type: 'M', feast: 'Thánh Gioan Maria Vianney, linh mục.', chasuble: 'Tr' },
        { date: '05/08', type: 'O', feast: 'Cung hiến thánh đường Đức Maria (Tr).' },
        { date: '07/08', type: 'O', feast: 'Thánh Xystô II, giáo hoàng, và các bạn, tử đạo (Đ). Thánh Cajêtanô, linh mục (Tr).' },
        { date: '08/08', type: 'M', feast: 'Thánh Đa Minh, linh mục.', chasuble: 'Tr' },
        { date: '09/08', type: 'O', feast: 'Thánh Têrêsa Bênêđicta, Thánh Giá, nữ tu, tử đạo (Đ).' },
        { date: '10/08', type: 'F', feast: 'THÁNH LAURENSÔ, PHÓ TẾ, TỬ ĐẠO.', chasuble: 'Đ' },
        { date: '11/08', type: 'M', feast: 'Thánh Clara, trinh nữ.', chasuble: 'Tr' },
        { date: '12/08', type: 'O', feast: 'Thánh Joanna Phanxica Chantal, nữ tu (Tr).' },
        { date: '13/08', type: 'O', feast: 'Thánh Pôntianô, giáo hoàng, tử đạo, và thánh Hippôlytô, linh mục, tử đạo (Đ).' },
        { date: '14/08', type: 'M', feast: 'Thánh Maximilianô Maria Kolbê, linh mục, tử đạo.', chasuble: 'Tr' },
        { date: '19/08', type: 'O', feast: 'Thánh Gioan Êuđê, linh mục (Tr).' },
        { date: '20/08', type: 'M', feast: 'Thánh Bêrnarđô, viện phụ, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '21/08', type: 'M', feast: 'Thánh Piô X, giáo hoàng.', chasuble: 'Tr' },
        { date: '22/08', type: 'M', feast: 'Đức Maria Nữ Vương. Lễ nhớ.', chasuble: 'Tr' },
        { date: '23/08', type: 'O', feast: 'Thánh Rôsa Lima, trinh nữ (Tr).' },
        { date: '24/08', type: 'F', feast: 'THÁNH BARTHÔLÔMÊO, TÔNG ĐỒ.', chasuble: 'Đ' },
        { date: '25/08', type: 'O', feast: 'Thánh Luy (Tr). Thánh Giuse Calasanz, linh mục (Tr).' },
        { date: '27/08', type: 'M', feast: 'Thánh Monica.', chasuble: 'Tr' },
        { date: '28/08', type: 'M', feast: 'Thánh Augustinô, giám mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '29/08', type: 'M', feast: 'Thánh Gioan Tẩy Giả bị trảm quyết.', chasuble: 'Đ' },

        {date: '01/09', type: 'O', feast: 'Cầu Cho Việc Bảo Vệ Công Trình Tạo Dựng.', chasuble: 'X' },
        { date: '02/09', type: 'O', feast: 'Ngày Quốc Khánh. Cầu bình an cho Tổ Quốc.' },
        { date: '03/09', type: 'M', feast: 'Thánh Grêgôriô Cả, giáo hoàng, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '05/09', type: 'O', feast: 'Thánh Têrêsa Calcutta, nữ tu (Tr).' },
        { date: '08/09', type: 'F', feast: 'SINH NHẬT ĐỨC ĐỨC TRINH NỮ MARIA.', chasuble: 'Tr' },
        { date: '09/09', type: 'O', feast: 'Thánh Phêrô Claver, linh mục (Tr).' },
        { date: '12/09', type: 'O', feast: 'Thánh Danh Đức Maria (Tr).' },
        { date: '13/09', type: 'M', feast: 'Thánh Gioan Kim Khẩu, giám mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '14/09', type: 'F', feast: 'SUY TÔN THÁNH GIÁ.', chasuble: 'Đ' },
        { date: '15/09', type: 'M', feast: 'Đức Mẹ sầu bi.', chasuble: 'Tr' },
        { date: '16/09', type: 'M', feast: 'Thánh Cornêniô, giáo hoàng, tử đạo và thánh Cyprianô, giám mục, tử đạo.', chasuble: 'Đ' },
        { date: '17/09', type: 'O', feast: 'Thánh Robertô Bellarminô, giám mục, tiến sĩ Hội Thánh (Tr).' },
        { date: '19/09', type: 'O', feast: 'Thánh Januariô, giám mục, tử đạo (Đ).' },
        { date: '20/09', type: 'M', feast: 'Thánh Anrê Kim Têgôn, linh mục, Phaolô Chong Hasang và các bạn, tử đạo.', chasuble: 'Đ' },
        { date: '21/09', type: 'F', feast: 'THÁNH MATTHÊU. TÔNG ĐỒ.', chasuble: 'Đ' },
        { date: '23/09', type: 'M', feast: 'Thánh Piô Pietrelcima, linh mục.', chasuble: 'Tr' },
        { date: '26/09', type: 'O', feast: 'Thánh Cosma và thánh Đamianô, tử đạo (Đ).' },
        { date: '27/09', type: 'M', feast: 'Thánh Vinh Sơn Phaolô (Vincente), linh mục.', chasuble: 'Tr' },
        { date: '28/09', type: 'O', feast: 'Thánh Venceslao, tử đạo (Đ). Thánh Laurensô Ruiz và các bạn, tử đạo (Đ).' },
        { date: '29/09', type: 'F', feast: 'CÁC TỔNG LÃNH THIÊN THẦN: THÁNH MICHAÊL, GABRIEL và RAPHAEL.', chasuble: 'Tr' },
        { date: '30/09', type: 'M', feast: 'Thánh Giêrônimô, linh mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },

       { date: '01/10', type: 'F', feast: 'THÁNH TÊRÊSA HÀI ĐỒNG GIÊSU, TRINH NỮ, TIẾN SĨ HỘI THÁNH, Bổn mạng các xứ truyền giáo.', chasuble: 'Tr' },
        { date: '02/10', type: 'M', feast: 'Các Thiên Thần Hộ Thủ.', chasuble: 'Tr' },
        { date: '04/10', type: 'M', feast: 'Thánh Phanxicô Assisi, linh mục.', chasuble: 'Tr' },
        { date: '05/10', type: 'O', feast: 'Thánh Maria Faustina Kôwalska, trinh nữ (Tr).' },
        { date: '06/10', type: 'O', feast: 'Thánh Brunô, linh mục (Tr).' },
        { date: '07/10', type: 'M', feast: 'Đức Mẹ Mân Côi.', chasuble: 'Tr' },
        { date: '09/10', type: 'O', feast: 'Thánh Đianysio, giám mục, và các bạn, tử đạo (Đ). Thánh Gioan Lêônarđo, linh mục (Tr).' },
        { date: '11/10', type: 'O', feast: 'Thánh Gioan XXIII, giáo hoàng (Tr).' },
        { date: '14/10', type: 'O', feast: 'Thánh Callistô I, giáo hoàng, tử đạo (Đ).' },
        { date: '15/10', type: 'M', feast: 'Thánh Têrêsa Giêsu (Avila), trinh nữ, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '16/10', type: 'O', feast: 'Thánh Hedviges, nữ tu (Tr). Thánh Margarita Alacoque, trinh nữ (Tr).' },
        { date: '17/10', type: 'M', feast: 'Thánh Ignatiô Antiôchia, Giám mục, tử đạo.', chasuble: 'Đ' },
        { date: '18/10', type: 'F', feast: 'THÁNH LUCA, TÁC GIẢ SÁCH TIN MỪNG.', chasuble: 'Đ' },
        { date: '19/10', type: 'O', feast: 'Thánh Gioan Brêbeuf, linh mục, thánh Isaac Jogues, linh mục, và các bạn, tử đạo (Đ). Thánh Phaolô Thánh Giá, linh mục (Tr).' },
        { date: '22/10', type: 'O', feast: 'Thánh Gioan Phaolô II, giáo hoàng (Tr).' },
        { date: '23/10', type: 'O', feast: 'Thánh Gioan Capestranô, linh mục (Tr).' },
        { date: '24/10', type: 'O', feast: 'Thánh Antôn Maria Claret, giám mục (Tr).' },
        { date: '28/10', type: 'F', feast: 'THÁNH SIMON VÀ THÁNH GIUĐA TÔNG ĐỒ.', chasuble: 'Đ' },

         { date: '01/11', type: 'S', feast: 'CÁC THÁNH NAM NỮ. Lễ trọng. Lễ cầu cho giáo dân (Lễ họ).', chasuble: 'Tr' },
        { date: '02/11', type: 'S', feast: 'CẦU CHO CÁC TÍN HỮU ĐÃ QUA ĐỜI.', chasuble: 'Tm' },
        { date: '03/11', type: 'O', feast: 'Thánh Martinô Porres, tu sĩ (Tr).' },
        { date: '04/11', type: 'M', feast: 'Thánh Carlô Borômêô, giám mục.', chasuble: 'Tr' },
        { date: '09/11', type: 'F', feast: 'CUNG HIẾN THÁNH ĐƯỜNG LATÊRANÔ.', chasuble: 'Tr' },
        { date: '10/11', type: 'M', feast: 'Thánh Lêô Cả. giáo hoàng, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '11/11', type: 'M', feast: 'Thánh Martinô, giám mục.', chasuble: 'Tr' },
        { date: '12/11', type: 'M', feast: 'Thánh Jôsaphát, giám mục, tử đạo.', chasuble: 'Đ' },
        { date: '15/11', type: 'O', feast: 'Thánh Albertô Cả, giám mục, tiến sĩ Hội Thánh (Tr).' },
        { date: '16/11', type: 'O', feast: 'Thánh nữ Magarita Scotland (Tr). Thánh Gertruđê, trinh nữ (Tr).' },
        { date: '17/11', type: 'M', feast: 'Thánh Nữ Êlisabeth Hungari.', chasuble: 'Tr' },
        { date: '18/11', type: 'O', feast: 'Cung hiến thánh đường thánh Phêrô và thánh đường thánh Phaolô (Tr).' },
        { date: '21/11', type: 'M', feast: 'Đức Mẹ dâng mình trong đền thờ.', chasuble: 'Tr' },
        { date: '22/11', type: 'M', feast: 'Thánh Cecilia, trinh nữ, tử đạo.', chasuble: 'Đ' },
        { date: '23/11', type: 'O', feast: 'Thánh Clêmentê I, giáo hoàng, tử đạo (Đ). Thánh Côlumbanô, viện phụ (Tr).' },
        { date: '25/11', type: 'O', feast: 'Thánh Catarina Alexanđria, trinh nữ, tử đạo (Đ).' },
        { date: '30/11', type: 'F', feast: 'THÁNH ANRÊ TÔNG ĐỒ.', chasuble: 'Đ' },

	      { date: '03/12', type: 'F', feast: 'THÁNH PHANXICÔ XAVIÊ, Linh mục. Bổn mạng các xứ truyền giáo.', chasuble: 'Tr' },
        { date: '04/12', type: 'O', feast: 'Thánh Gioan Đamas, linh mục, tiến sĩ Hội Thánh (Tr).' },
        { date: '06/12', type: 'O', feast: 'Thánh Nicôla, giám mục (Tr).' },
        { date: '07/12', type: 'M', feast: 'Thánh Ambrôsiô, giám mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '09/12', type: 'O', feast: 'Thánh Gioan Điđacô (Tr).' },
        { date: '10/12', type: 'O', feast: 'Đức Mẹ Loretô (Tr).' },
        { date: '12/12', type: 'O', feast: 'Đức Mẹ Guađalupê (Tr).' },
        { date: '14/12', type: 'M', feast: 'Thánh Gioan Thánh Giá, linh mục, tiến sĩ Hội Thánh.', chasuble: 'Tr' },
        { date: '21/12', type: 'O', feast: 'Thánh Phêrô Canisiô, linh mục, tiến sĩ Hội Thánh.' },
        { date: '23/12', type: 'O', feast: 'Thánh Gioan Kêty, linh mục.' },
        { date: '26/12', type: 'F', feast: 'THÁNH STÊPHANÔ, TỬ ĐẠO TIÊN KHỞI.', chasuble: 'Đ' },
        { date: '27/12', type: 'F', feast: 'THÁNH GIOAN, TÔNG ĐỒ. TÁC GIẢ TIN MỪNG.', chasuble: 'Đ' },
        { date: '28/12', type: 'F', feast: 'CÁC THÁNH ANH HÀI TỬ ĐẠO.', chasuble: 'Đ' },
        { date: '31/12', type: '0', feast: 'Thánh Sylvestro, giáo hoàng.'},
    ];

