window.eucharisticAdoration = {
    
"01":{"content": "Chầu Thánh Thể tại: Tân Rai – B’Đơr – Đoàn Kết – Tân Hà"},
"02":{"content": "Chầu Thánh Thể tại: Cát Tiên – Thánh Tâm (LT) – Phú Hiệp"},
"03":{"content":"Chầu Thánh Thể tại: Đv. Châu Sơn – Tân Hóa – Ninh Gia" },
"04":{"content":"Chầu Thánh Thể tại: Tân Bình – Suối Mơ – B’Sumrắc"},
"05":{"content":"Chầu Thánh Thể tại: Tùng Lâm – Lộc Đức – Vinh Sơn Liêm"},
"06":{"content":"Chầu Thánh Thể tại: K’Long – Đức Giang – Lê Bảo Tịnh (Bảo Lâm)"},
"07":{"content":"Chầu Thánh Thể tại: Tân Lạc – Đưng Kơnơh – Liêng Srônh – Đạ Tông"},
"08":{"content":"Chầu Thánh Thể tại: Mẹ Hằng Cứu Giúp – Tu Tra - Đồng Nai Thượng"},
"09":{"content":"Chầu Thánh Thể tại: Bảo Lộc – Tà Nung – Gs. Đạ Lơ Nghệt"},
"10":{"content":"Chầu Thánh Thể tại: Proh – Lâm Phát – Gs. Hòa Trung"},
"11":{"content":"Chầu Thánh Thể tại: Chánh Tòa – Ka Đơn – Liang Dăm – B’Lát"},
"12":{"content":"Chầu Thánh Thể tại: Nam Ban – Tân Nghĩa – Thạnh Mỹ – Minh Rồng"},
"13":{"content":"Chầu Thánh Thể tại: Lán Tranh – Tân Bùi – Thượng Thanh"},
"14":{"content":"Chầu Thánh Thể tại: Tam Bố – Tân Thanh – Gs. Tà Năng"},
"15":{"content":"Chầu Thánh Thể tại: Tân Phú – Thánh Giuse (TB) – ĐCV. Minh Hòa"},
"16":{"content":"Chầu Thánh Thể tại: Liên Khương – Đinh Trang Hòa – Lộc Nam"},
"17":{"content":"Chầu Thánh Thể tại: MTG. Đà Lạt – Tv. Lâm Viên (KT)"},
"18":{"content":"Chầu Thánh Thể tại: Ninh Loan – Bạch Đằng – Gs. Tân Đức"},
"19":{"content":"Chầu Thánh Thể tại: Hòa Nam – Đức Mẹ Vô Nhiễm – Chân Lộc"},
"20":{"content":"Chầu Thánh Thể tại: An Hòa – Thanh Xuân – Lạc Viên"},
"21":{"content":"Chầu Thánh Thể tại: Tân Lâm – Thánh Tâm (LP) - Gs.Thánh Tâm (ĐL) – Lạc Sơn"},
"22":{"content":"Chầu Thánh Thể tại: Nam Phương – Đv. Biển Đức Lộc Nam"},
"23":{"content":"Chầu Thánh Thể tại: Gioan – Gia Lành – Gs. Martinô"},
"24":{"content":"Chầu Thánh Thể tại: Suối Thông – Tân Thành – Gia Bắc"},
"25":{"content":"Chầu Thánh Thể tại: Mađaguôi – K’ Nai – Di Linh – Hòa Bắc"},
"26":{"content":"Chầu Thánh Thể tại: Thiện Lộc – Lạc Nghiệp – Gân Reo"},
"27":{"content":"Chầu Thánh Thể tại: Lạc Lâm – Lê Bảo Tịnh (B. Lộc) - Xà Lùng – Tạo Tác"},
"28":{"content":"Chầu Thánh Thể tại: Tùng Nghĩa – Du Sinh – Gs. Ngọc Long"},
"29":{"content":"Chầu Thánh Thể tại: Thanh Bình – Thanh Xá  – Chúa Kitô Vua"},
"30":{"content":"Chầu Thánh Thể tại: Kala – Trại Phong Di Linh – Đinh Văn – Đức Thanh"},
"31":{"content":"Chầu Thánh Thể tại: Mai Anh – Diom – Tv. Trinh Vương Phú Hiệp"},
"32":{"content":"Chầu Thánh Thể tại: Chi Lăng & Trại Hầm – Phúc Lộc – Mỹ Đức"},
"33":{"content":"Chầu Thánh Thể tại: Đạ Tẻh – Đạ Nha – Đa Lộc"},
"34":{"content":"Chầu Thánh Thể tại: Đambri – Châu Sơn – Phi Tô"},
"35":{"content":"Chầu Thánh Thể tại: Kim Phát – Phát Chi – Tv. Thiên Hương Đà Lạt"},
"36":{"content":"Chầu Thánh Thể tại: Tân Văn – Păng Tiêng – Hiệp Phát"},
"37":{"content":"Chầu Thánh Thể tại: Đại Lộc – Đa Thiện – Lộc An – R’Lơm"},
"38":{"content":"Chầu Thánh Thể tại: Hòa Phát – Hàng Hải – Lạc Hòa"},
"39":{"content":"Chầu Thánh Thể tại: Thánh Giuse (LH) – Đv. Cát Minh ĐL – Đam Pao"},
"40":{"content":"Chầu Thánh Thể tại: Hòa Ninh – Gs. Don Bosco – Phaolô"},
"41":{"content":"Chầu Thánh Thể tại: Cầu Đất – Kaming – Tà In – Phú Sơn"},
"42":{"content":"Chầu Thánh Thể tại: Vinh Sơn – Tv. Trinh Vương Đà Lạt"},
"43":{"content":"Chầu Thánh Thể tại: Bắc Hội – Quảng Lâm – Sơn Điền"},
"44":{"content":"Chầu Thánh Thể tại: Nghĩa Lâm – Đà Loan – Phước Cát"},
"45":{"content":"Chầu Thánh Thể tại: Mẹ Thiên Chúa – Đạ K’Nàng – B’Lá"},
"46":{"content":"Chầu Thánh Thể tại: Minh Giáo – Phi Liêng – Dòng Chứng Nhân ĐT"},
"47":{"content":"Chầu Thánh Thể tại: Thiện Lâm – Vạn Thành – Đaminh – Tân Thành"},
"48":{"content":"Chầu Thánh Thể tại: Thánh Mẫu (ĐL)"},
"49":{"content":"Chầu Thánh Thể tại: Gs. Định An –  An Bình"},
"50":{"content":"Chầu Thánh Thể tại: Thánh Mẫu (LP) – K’Rèn"},
"51":{"content":"Chầu Thánh Thể tại: Hà Đông – La Vang – Tv. Phanxicô"},
"52":{"content":"Chầu Thánh Thể tại: Langbiang – Đạ R’Sal"},
"53":{"content":""}

};

